---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "hl-composer.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  accessModes: {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.capacity }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}