apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-ord.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  CA_ADDRESS: {{ .Values.caAddress | b64enc | quote }}
