core:
  # Comment out to make it work on your cluster
  cluster: minikube
  # AT_Charts directory holding charts
  chart_repo: ./
  # Directory where we hold configtx.yaml
  dir_config: ./networks/qa/config
  # Directory where we hold:
  # 1) cryptographic material
  # 2) genesis block and
  # 3) channel transaction
  dir_crypto: ./networks/qa/crypto
  # Directory where the Helm Chart values reside
  dir_values: ./networks/qa/helm_values
cas:
  ca:
    namespace: cas
    # If testing locally on Minikube, we use our own self-signed certificate's PEM
    tls_cert: ./networks/ca-nephos-local.pem
    # Alternatively, if testing on a cluster with proper DNS and cert-manager...
    #tls_cert: ./nephos/extras/Lets_Encrypt_Authority_X3.pem
msps:
  OrdererMSP:
    ca: ca
    namespace: orderers
    org_admin: ordadmin
  PeerMSP:
    ca: ca
    namespace: peers
    org_admin: peeradmin
orderers:
  domain: orderers.svc.cluster.local
  msp: OrdererMSP
  names:
  - ord1
  secret_genesis: hlf--genesis
peers:
  domain: peers.svc.cluster.local
  msp: PeerMSP
  names:
  - peer1
  channel_name: mychannel
  channel_profile: MyChannel
  secret_channel: hlf--channel
# This is only used when we implement a Composer network
composer:
  name: hlc
  secret_bna: hlc--bna
  secret_connection: hlc--connection
